language: python
virtualenv:
  system_site_packages: false
sudo: true
matrix:
  include:
    - dist: xenial
      env: ENV=pep8
      python: 3.5
    - dist: xenial
      env: ENV=py3
      python: 3.5
    - dist: xenial
      env: ENV=func-travis
      python: 3.5
    - dist: bionic
      env: ENV=pep8
      python: 3.6
    - dist: bionic
      env: ENV=py3
      python: 3.6
    - dist: bionic
      env: ENV=func-travis
      python: 3.6
    - dist: bionic
      env: ENV=pep8
      python: 3.7
    - dist: bionic
      env: ENV=py3
      python: 3.7
    - dist: bionic
      env: ENV=func-travis
      python: 3.7
before_install:
  - if [ $ENV = 'func-travis' ]; then
       sudo apt remove -y --purge lxd lxd-client;
       sudo snap install lxd;
       sudo snap install juju --classic;
       sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment';
       sudo lxd waitready;
       sudo lxd init --auto;
       sudo usermod -a -G lxd travis;
       sudo su travis -c 'juju bootstrap --debug --no-gui localhost';
    fi
install:
  - pip install tox-travis
script:
  - tox -e $ENV
  - if [ $ENV = 'func-travis' ]; then
       sudo su travis -c 'juju status -m $(juju models --format yaml|grep "^- name:.*zaza"|cut -f2 -d/)';
    fi
